/**
 * Seed script for Sanity content.
 *
 * Usage:
 *   SANITY_PROJECT_ID=xxx SANITY_DATASET=production SANITY_TOKEN=xxx node scripts/seed-sanity.mjs
 *
 * The SANITY_TOKEN must have write access (create a token in Sanity > API > Tokens).
 */

import { createClient } from "@sanity/client";

const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET ?? "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_TOKEN,
  useCdn: false,
});

// ─── Taxonomy ────────────────────────────────────────────────────────────────

const technologies = [
  { _id: "tech-kafka", title: "Apache Kafka", slug: "apache-kafka", color: "#232323" },
  { _id: "tech-postgresql", title: "PostgreSQL", slug: "postgresql", color: "#336791" },
  { _id: "tech-mysql", title: "MySQL", slug: "mysql", color: "#4479A1" },
  { _id: "tech-opensearch", title: "OpenSearch", slug: "opensearch", color: "#005EB8" },
  { _id: "tech-clickhouse", title: "ClickHouse", slug: "clickhouse", color: "#FFCC00" },
  { _id: "tech-flink", title: "Apache Flink", slug: "apache-flink", color: "#E6526F" },
  { _id: "tech-cassandra", title: "Apache Cassandra", slug: "apache-cassandra", color: "#1287B1" },
  { _id: "tech-valkey", title: "Valkey", slug: "valkey", color: "#DC382D" },
  { _id: "tech-dragonfly", title: "Dragonfly", slug: "dragonfly", color: "#6C5CE7" },
  { _id: "tech-redis", title: "Redis", slug: "redis", color: "#DC382D" },
  { _id: "tech-pgvector", title: "pgvector", slug: "pgvector", color: "#336791" },
];

const topics = [
  { _id: "topic-ai", title: "AI", slug: "ai" },
  { _id: "topic-cloud-data-platform", title: "Cloud Data Platform", slug: "cloud-data-platform" },
  { _id: "topic-cost-optimization", title: "Cost Optimization", slug: "cost-optimization" },
  { _id: "topic-event-streaming", title: "Event Streaming", slug: "event-streaming" },
  { _id: "topic-open-source", title: "Open Source", slug: "open-source" },
  { _id: "topic-real-time-analytics", title: "Real-Time Analytics", slug: "real-time-analytics" },
  { _id: "topic-machine-learning", title: "Machine Learning", slug: "machine-learning" },
  { _id: "topic-byoc", title: "BYOC", slug: "byoc" },
  { _id: "topic-devops", title: "DevOps", slug: "devops" },
  { _id: "topic-performance", title: "Performance Optimization", slug: "performance-optimization" },
  { _id: "topic-roi", title: "ROI", slug: "roi" },
  { _id: "topic-sustainability", title: "Sustainability", slug: "sustainability" },
  { _id: "topic-security", title: "Security", slug: "security" },
  { _id: "topic-migration", title: "Migration", slug: "migration" },
];

const personas = [
  { _id: "persona-developer", title: "Developer", slug: "developer", description: "Software engineers building applications on data infrastructure." },
  { _id: "persona-platform-engineer", title: "Platform Engineer", slug: "platform-engineer", description: "Infrastructure engineers managing data platforms at scale." },
  { _id: "persona-engineering-leader", title: "Engineering Leader", slug: "engineering-leader", description: "Engineering managers and directors making technical strategy decisions." },
  { _id: "persona-c-suite", title: "C-Suite", slug: "c-suite", description: "CTOs, CIOs, and VPs evaluating data platform strategy." },
];

// ─── Resources ───────────────────────────────────────────────────────────────

const resources = [
  // E-books (8)
  {
    title: "The Complete Guide to Apache Kafka Management",
    slug: "complete-guide-kafka-management",
    description: "Everything you need to know about running Kafka in production — from cluster sizing to monitoring, security, and multi-region replication.",
    contentType: "ebook",
    technologies: ["tech-kafka"],
    topics: ["topic-event-streaming", "topic-devops"],
    personas: ["persona-platform-engineer", "persona-developer"],
    featured: true,
    duration: "45 min read",
    publishedAt: "2025-11-15T10:00:00Z",
  },
  {
    title: "Real-Time Data Pipelines: Architecture Patterns",
    slug: "real-time-data-pipelines-patterns",
    description: "Architectural blueprints for building low-latency data pipelines using Kafka, Flink, and ClickHouse.",
    contentType: "ebook",
    technologies: ["tech-kafka", "tech-flink", "tech-clickhouse"],
    topics: ["topic-event-streaming", "topic-real-time-analytics"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "1 hr read",
    publishedAt: "2025-10-02T10:00:00Z",
  },
  {
    title: "Cloud Database Migration Handbook",
    slug: "cloud-database-migration-handbook",
    description: "A step-by-step guide to migrating PostgreSQL, MySQL, and Cassandra workloads to managed cloud services without downtime.",
    contentType: "ebook",
    technologies: ["tech-postgresql", "tech-mysql", "tech-cassandra"],
    topics: ["topic-migration", "topic-cloud-data-platform"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: false,
    duration: "50 min read",
    publishedAt: "2025-09-18T10:00:00Z",
  },
  {
    title: "Building AI Applications with pgvector",
    slug: "building-ai-applications-pgvector",
    description: "How to use PostgreSQL and pgvector for vector similarity search, RAG pipelines, and embedding storage in production AI systems.",
    contentType: "ebook",
    technologies: ["tech-postgresql", "tech-pgvector"],
    topics: ["topic-ai", "topic-machine-learning"],
    personas: ["persona-developer"],
    featured: true,
    duration: "35 min read",
    publishedAt: "2025-12-01T10:00:00Z",
  },
  {
    title: "Multi-Cloud Data Strategy for Enterprises",
    slug: "multi-cloud-data-strategy",
    description: "How leading enterprises architect their data infrastructure across AWS, GCP, and Azure to avoid lock-in and optimize costs.",
    contentType: "ebook",
    technologies: [],
    topics: ["topic-cloud-data-platform", "topic-cost-optimization"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "40 min read",
    publishedAt: "2025-08-22T10:00:00Z",
  },
  {
    title: "The Open Source Data Infrastructure Playbook",
    slug: "open-source-data-infrastructure-playbook",
    description: "Why open source databases and streaming platforms are winning, and how to build a sustainable open source data stack.",
    contentType: "ebook",
    technologies: ["tech-kafka", "tech-postgresql", "tech-opensearch"],
    topics: ["topic-open-source", "topic-cloud-data-platform"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "30 min read",
    publishedAt: "2025-07-10T10:00:00Z",
  },
  {
    title: "Kafka Connect: Integrations Deep Dive",
    slug: "kafka-connect-integrations-deep-dive",
    description: "Master Kafka Connect with hands-on examples for PostgreSQL CDC, OpenSearch sinks, S3 archival, and custom connector development.",
    contentType: "ebook",
    technologies: ["tech-kafka", "tech-postgresql", "tech-opensearch"],
    topics: ["topic-event-streaming", "topic-devops"],
    personas: ["persona-developer"],
    featured: false,
    duration: "55 min read",
    publishedAt: "2025-06-05T10:00:00Z",
  },
  {
    title: "Cost Optimization Strategies for Data Infrastructure",
    slug: "cost-optimization-data-infrastructure",
    description: "Proven strategies to reduce your cloud data infrastructure costs by 30-50% without sacrificing performance or reliability.",
    contentType: "ebook",
    technologies: [],
    topics: ["topic-cost-optimization", "topic-roi", "topic-cloud-data-platform"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "25 min read",
    publishedAt: "2025-05-20T10:00:00Z",
  },

  // Webinars (8)
  {
    title: "From Batch to Real-Time: Modernizing Your Data Architecture",
    slug: "batch-to-realtime-modernizing-data",
    description: "Learn how companies are shifting from overnight ETL jobs to real-time streaming architectures using Kafka and Flink.",
    contentType: "webinar",
    technologies: ["tech-kafka", "tech-flink"],
    topics: ["topic-event-streaming", "topic-real-time-analytics"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: true,
    duration: "55 min",
    publishedAt: "2025-12-10T14:00:00Z",
  },
  {
    title: "PostgreSQL Performance Tuning Masterclass",
    slug: "postgresql-performance-tuning-masterclass",
    description: "Advanced techniques for query optimization, index strategies, connection pooling, and resource management in PostgreSQL.",
    contentType: "webinar",
    technologies: ["tech-postgresql"],
    topics: ["topic-performance", "topic-devops"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "60 min",
    publishedAt: "2025-11-28T14:00:00Z",
  },
  {
    title: "GenAI Data Infrastructure: What CTOs Need to Know",
    slug: "genai-data-infrastructure-ctos",
    description: "A strategic overview of the data infrastructure requirements for deploying generative AI at enterprise scale.",
    contentType: "webinar",
    technologies: ["tech-pgvector", "tech-opensearch"],
    topics: ["topic-ai", "topic-cloud-data-platform"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: true,
    duration: "45 min",
    publishedAt: "2025-12-05T14:00:00Z",
  },
  {
    title: "Zero-Downtime Database Migrations in Practice",
    slug: "zero-downtime-database-migrations",
    description: "Real-world patterns for migrating live databases between cloud providers and versions without affecting production traffic.",
    contentType: "webinar",
    technologies: ["tech-postgresql", "tech-mysql"],
    topics: ["topic-migration", "topic-devops"],
    personas: ["persona-platform-engineer", "persona-developer"],
    featured: false,
    duration: "50 min",
    publishedAt: "2025-10-15T14:00:00Z",
  },
  {
    title: "Building Observable Data Pipelines",
    slug: "building-observable-data-pipelines",
    description: "How to instrument your Kafka pipelines with metrics, tracing, and alerting for production-grade observability.",
    contentType: "webinar",
    technologies: ["tech-kafka"],
    topics: ["topic-devops", "topic-event-streaming"],
    personas: ["persona-platform-engineer"],
    featured: false,
    duration: "45 min",
    publishedAt: "2025-09-20T14:00:00Z",
  },
  {
    title: "ClickHouse for Real-Time Analytics: Getting Started",
    slug: "clickhouse-realtime-analytics-getting-started",
    description: "An introduction to ClickHouse's columnar architecture, query patterns, and how to build dashboards that query billions of rows in milliseconds.",
    contentType: "webinar",
    technologies: ["tech-clickhouse"],
    topics: ["topic-real-time-analytics"],
    personas: ["persona-developer"],
    featured: false,
    duration: "40 min",
    publishedAt: "2025-08-12T14:00:00Z",
  },
  {
    title: "Securing Your Data Platform: Best Practices",
    slug: "securing-data-platform-best-practices",
    description: "Encryption at rest, in transit, RBAC, audit logging, and compliance frameworks for managed data services.",
    contentType: "webinar",
    technologies: ["tech-kafka", "tech-postgresql"],
    topics: ["topic-security", "topic-cloud-data-platform"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: false,
    duration: "50 min",
    publishedAt: "2025-07-25T14:00:00Z",
  },
  {
    title: "BYOC: Running Managed Services in Your Own Cloud",
    slug: "byoc-managed-services-your-cloud",
    description: "Deep dive into Bring Your Own Cloud deployment models — architecture, networking, security, and cost implications.",
    contentType: "webinar",
    technologies: [],
    topics: ["topic-byoc", "topic-cloud-data-platform", "topic-security"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "45 min",
    publishedAt: "2025-06-18T14:00:00Z",
  },

  // Podcasts (8)
  {
    title: "The Future of Open Source Data Infrastructure",
    slug: "future-open-source-data-infrastructure",
    description: "Industry leaders discuss the sustainability, licensing challenges, and innovation happening in open source data systems.",
    contentType: "podcast",
    technologies: ["tech-kafka", "tech-postgresql", "tech-valkey"],
    topics: ["topic-open-source"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "38 min",
    publishedAt: "2025-11-20T10:00:00Z",
  },
  {
    title: "Streaming at Scale: Lessons from Fintech",
    slug: "streaming-at-scale-lessons-fintech",
    description: "How financial services companies process millions of events per second using Kafka and real-time fraud detection pipelines.",
    contentType: "podcast",
    technologies: ["tech-kafka", "tech-flink"],
    topics: ["topic-event-streaming", "topic-real-time-analytics"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "42 min",
    publishedAt: "2025-10-25T10:00:00Z",
  },
  {
    title: "AI-Native Databases: What Changes?",
    slug: "ai-native-databases-what-changes",
    description: "Exploring how vector databases, pgvector, and AI-optimized storage engines are reshaping the database landscape.",
    contentType: "podcast",
    technologies: ["tech-pgvector", "tech-postgresql"],
    topics: ["topic-ai", "topic-machine-learning"],
    personas: ["persona-developer", "persona-engineering-leader"],
    featured: false,
    duration: "35 min",
    publishedAt: "2025-09-30T10:00:00Z",
  },
  {
    title: "Platform Engineering: Building Golden Paths for Data",
    slug: "platform-engineering-golden-paths-data",
    description: "How platform teams are creating self-service data infrastructure that developers actually want to use.",
    contentType: "podcast",
    technologies: [],
    topics: ["topic-devops", "topic-cloud-data-platform"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: false,
    duration: "40 min",
    publishedAt: "2025-08-28T10:00:00Z",
  },
  {
    title: "The Economics of Managed vs Self-Hosted Databases",
    slug: "economics-managed-vs-self-hosted",
    description: "A frank discussion about the true total cost of ownership when comparing managed database services to self-hosted alternatives.",
    contentType: "podcast",
    technologies: ["tech-postgresql", "tech-kafka"],
    topics: ["topic-cost-optimization", "topic-roi"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "45 min",
    publishedAt: "2025-07-15T10:00:00Z",
  },
  {
    title: "Cassandra in 2025: Renaissance or Relic?",
    slug: "cassandra-2025-renaissance-or-relic",
    description: "Evaluating Cassandra's role in modern data architectures — when it's still the right choice and when to consider alternatives.",
    contentType: "podcast",
    technologies: ["tech-cassandra"],
    topics: ["topic-cloud-data-platform"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "33 min",
    publishedAt: "2025-06-22T10:00:00Z",
  },
  {
    title: "Green Data Centers: Sustainability in Cloud Infrastructure",
    slug: "green-data-centers-sustainability",
    description: "How cloud providers and managed service companies are reducing the carbon footprint of data infrastructure.",
    contentType: "podcast",
    technologies: [],
    topics: ["topic-sustainability", "topic-cloud-data-platform"],
    personas: ["persona-c-suite"],
    featured: false,
    duration: "36 min",
    publishedAt: "2025-05-10T10:00:00Z",
  },
  {
    title: "From Monolith to Microservices: Data Patterns",
    slug: "monolith-to-microservices-data-patterns",
    description: "The data architecture decisions that make or break a microservices migration — event sourcing, CQRS, and saga patterns.",
    contentType: "podcast",
    technologies: ["tech-kafka", "tech-postgresql"],
    topics: ["topic-event-streaming", "topic-devops"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "44 min",
    publishedAt: "2025-04-18T10:00:00Z",
  },

  // Tools (6)
  {
    title: "Kafka Throughput Calculator",
    slug: "kafka-throughput-calculator",
    description: "Estimate your Kafka cluster's throughput capacity based on partition count, message size, replication factor, and consumer group configuration.",
    contentType: "tool",
    technologies: ["tech-kafka"],
    topics: ["topic-performance", "topic-cost-optimization"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "Interactive",
    publishedAt: "2025-11-01T10:00:00Z",
  },
  {
    title: "PostgreSQL Query Optimizer",
    slug: "postgresql-query-optimizer",
    description: "Paste your slow query and get AI-powered optimization suggestions — index recommendations, query rewrites, and EXPLAIN analysis.",
    contentType: "tool",
    technologies: ["tech-postgresql"],
    topics: ["topic-performance"],
    personas: ["persona-developer"],
    featured: true,
    duration: "Interactive",
    publishedAt: "2025-10-20T10:00:00Z",
  },
  {
    title: "Cloud Cost Comparison Calculator",
    slug: "cloud-cost-comparison-calculator",
    description: "Compare the total cost of running your data infrastructure across AWS, GCP, Azure, and Aiven with detailed breakdowns.",
    contentType: "tool",
    technologies: [],
    topics: ["topic-cost-optimization", "topic-roi"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "Interactive",
    publishedAt: "2025-09-15T10:00:00Z",
  },
  {
    title: "Schema Registry Explorer",
    slug: "schema-registry-explorer",
    description: "Visualize and manage your Kafka Schema Registry — browse schemas, check compatibility, and simulate schema evolution.",
    contentType: "tool",
    technologies: ["tech-kafka"],
    topics: ["topic-event-streaming", "topic-devops"],
    personas: ["persona-developer"],
    featured: false,
    duration: "Interactive",
    publishedAt: "2025-08-05T10:00:00Z",
  },
  {
    title: "Database Migration Readiness Assessment",
    slug: "database-migration-readiness-assessment",
    description: "Answer 15 questions about your current database setup and get a personalized migration plan with risk assessment and timeline estimate.",
    contentType: "tool",
    technologies: ["tech-postgresql", "tech-mysql", "tech-cassandra"],
    topics: ["topic-migration"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: false,
    duration: "10 min",
    publishedAt: "2025-07-01T10:00:00Z",
  },
  {
    title: "Flink Job Visualizer",
    slug: "flink-job-visualizer",
    description: "Upload your Flink job graph and get an interactive visualization of your streaming pipeline topology with bottleneck detection.",
    contentType: "tool",
    technologies: ["tech-flink"],
    topics: ["topic-event-streaming", "topic-performance"],
    personas: ["persona-developer"],
    featured: false,
    duration: "Interactive",
    publishedAt: "2025-06-12T10:00:00Z",
  },

  // Reports (4)
  {
    title: "State of Data Infrastructure 2026",
    slug: "state-of-data-infrastructure-2026",
    description: "Annual survey of 2,000+ engineering leaders on database adoption, cloud spending, AI infrastructure, and platform engineering trends.",
    contentType: "report",
    technologies: [],
    topics: ["topic-cloud-data-platform", "topic-ai"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: true,
    duration: "20 min read",
    publishedAt: "2026-01-15T10:00:00Z",
  },
  {
    title: "The Economic Impact of Managed Data Services",
    slug: "economic-impact-managed-data-services",
    description: "Forrester TEI study measuring the ROI of switching from self-managed to fully managed data infrastructure across 12 enterprise customers.",
    contentType: "report",
    technologies: [],
    topics: ["topic-roi", "topic-cost-optimization"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "15 min read",
    publishedAt: "2025-10-01T10:00:00Z",
  },
  {
    title: "C-Suite AI Readiness Report",
    slug: "c-suite-ai-readiness-report",
    description: "How ready is your organization's data infrastructure for AI? Survey data from 500 CTOs and CIOs on GenAI adoption blockers.",
    contentType: "report",
    technologies: ["tech-pgvector"],
    topics: ["topic-ai", "topic-machine-learning"],
    personas: ["persona-c-suite"],
    featured: false,
    duration: "18 min read",
    publishedAt: "2025-08-15T10:00:00Z",
  },
  {
    title: "Carbon Footprint of Cloud Databases",
    slug: "carbon-footprint-cloud-databases",
    description: "Measuring and reducing the environmental impact of database workloads — benchmarks, best practices, and provider comparisons.",
    contentType: "report",
    technologies: [],
    topics: ["topic-sustainability"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "12 min read",
    publishedAt: "2025-05-01T10:00:00Z",
  },

  // Workshops (5)
  {
    title: "Hands-On: Build a Streaming ETL Pipeline",
    slug: "hands-on-streaming-etl-pipeline",
    description: "Build a complete streaming ETL pipeline from PostgreSQL CDC through Kafka to ClickHouse using Kafka Connect and Flink SQL.",
    contentType: "workshop",
    technologies: ["tech-kafka", "tech-postgresql", "tech-clickhouse", "tech-flink"],
    topics: ["topic-event-streaming", "topic-real-time-analytics"],
    personas: ["persona-developer"],
    featured: false,
    duration: "2 hrs",
    publishedAt: "2025-11-05T10:00:00Z",
  },
  {
    title: "PostgreSQL Administration Fundamentals",
    slug: "postgresql-administration-fundamentals",
    description: "From installation to production-ready — backup strategies, replication setup, monitoring, and security hardening for PostgreSQL.",
    contentType: "workshop",
    technologies: ["tech-postgresql"],
    topics: ["topic-devops"],
    personas: ["persona-platform-engineer", "persona-developer"],
    featured: false,
    duration: "3 hrs",
    publishedAt: "2025-09-10T10:00:00Z",
  },
  {
    title: "Kafka Streams: Stateful Processing Workshop",
    slug: "kafka-streams-stateful-processing",
    description: "Learn to build stateful stream processing applications with Kafka Streams — windowing, joins, state stores, and exactly-once semantics.",
    contentType: "workshop",
    technologies: ["tech-kafka"],
    topics: ["topic-event-streaming"],
    personas: ["persona-developer"],
    featured: false,
    duration: "2.5 hrs",
    publishedAt: "2025-07-20T10:00:00Z",
  },
  {
    title: "OpenSearch: Full-Text Search & Observability",
    slug: "opensearch-full-text-search-observability",
    description: "Build a search engine and log analytics platform using OpenSearch — indexing strategies, query DSL, dashboards, and alerting.",
    contentType: "workshop",
    technologies: ["tech-opensearch"],
    topics: ["topic-devops", "topic-real-time-analytics"],
    personas: ["persona-developer", "persona-platform-engineer"],
    featured: false,
    duration: "2 hrs",
    publishedAt: "2025-06-01T10:00:00Z",
  },
  {
    title: "Vector Search with pgvector: From Zero to Production",
    slug: "vector-search-pgvector-zero-to-production",
    description: "Hands-on workshop building a semantic search application with pgvector — embedding generation, indexing strategies, and query optimization.",
    contentType: "workshop",
    technologies: ["tech-postgresql", "tech-pgvector"],
    topics: ["topic-ai", "topic-machine-learning"],
    personas: ["persona-developer"],
    featured: false,
    duration: "2 hrs",
    publishedAt: "2025-04-15T10:00:00Z",
  },

  // White Papers (4)
  {
    title: "Data Mesh on Managed Services: A Reference Architecture",
    slug: "data-mesh-managed-services-reference",
    description: "How to implement data mesh principles using managed databases and streaming services — domain ownership, data products, and self-serve infrastructure.",
    contentType: "white-paper",
    technologies: ["tech-kafka", "tech-postgresql", "tech-clickhouse"],
    topics: ["topic-cloud-data-platform", "topic-devops"],
    personas: ["persona-engineering-leader", "persona-platform-engineer"],
    featured: false,
    duration: "25 min read",
    publishedAt: "2025-10-12T10:00:00Z",
  },
  {
    title: "Event-Driven Architecture: Patterns and Anti-Patterns",
    slug: "event-driven-architecture-patterns",
    description: "A comprehensive analysis of event-driven patterns including event sourcing, CQRS, choreography vs orchestration, and common failure modes.",
    contentType: "white-paper",
    technologies: ["tech-kafka"],
    topics: ["topic-event-streaming"],
    personas: ["persona-developer", "persona-engineering-leader"],
    featured: false,
    duration: "30 min read",
    publishedAt: "2025-08-20T10:00:00Z",
  },
  {
    title: "Compliance and Data Residency in Multi-Region Deployments",
    slug: "compliance-data-residency-multi-region",
    description: "Navigating GDPR, SOC 2, HIPAA, and data sovereignty requirements when running databases across multiple cloud regions.",
    contentType: "white-paper",
    technologies: [],
    topics: ["topic-security", "topic-cloud-data-platform"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "20 min read",
    publishedAt: "2025-06-25T10:00:00Z",
  },
  {
    title: "The Total Cost of Downtime: Database Reliability Engineering",
    slug: "total-cost-downtime-reliability-engineering",
    description: "Quantifying the business impact of database outages and a framework for building reliability into your data infrastructure from day one.",
    contentType: "white-paper",
    technologies: ["tech-postgresql", "tech-kafka"],
    topics: ["topic-roi", "topic-performance"],
    personas: ["persona-c-suite", "persona-engineering-leader"],
    featured: false,
    duration: "22 min read",
    publishedAt: "2025-04-05T10:00:00Z",
  },

  // Live Videos (3)
  {
    title: "Inside Aiven: How We Run Kafka at Massive Scale",
    slug: "inside-aiven-kafka-massive-scale",
    description: "An inside look at how Aiven manages tens of thousands of Kafka clusters — automation, fleet management, and incident response.",
    contentType: "live-video",
    technologies: ["tech-kafka"],
    topics: ["topic-devops", "topic-cloud-data-platform"],
    personas: ["persona-platform-engineer", "persona-engineering-leader"],
    featured: false,
    duration: "32 min",
    publishedAt: "2025-11-08T14:00:00Z",
  },
  {
    title: "Panel: The State of Open Source in Financial Services",
    slug: "panel-open-source-financial-services",
    description: "Industry panel with engineering leaders from fintech companies discussing open source adoption, compliance, and operational challenges.",
    contentType: "live-video",
    technologies: ["tech-kafka", "tech-postgresql"],
    topics: ["topic-open-source"],
    personas: ["persona-engineering-leader", "persona-c-suite"],
    featured: false,
    duration: "48 min",
    publishedAt: "2025-09-05T14:00:00Z",
  },
  {
    title: "Demo: Real-Time Fraud Detection with Flink and Kafka",
    slug: "demo-realtime-fraud-detection-flink-kafka",
    description: "Live coding demo building a fraud detection system that processes payment events in real-time using Flink SQL and Kafka.",
    contentType: "live-video",
    technologies: ["tech-kafka", "tech-flink"],
    topics: ["topic-event-streaming", "topic-real-time-analytics"],
    personas: ["persona-developer"],
    featured: false,
    duration: "28 min",
    publishedAt: "2025-07-30T14:00:00Z",
  },
];

// ─── Seed Logic ──────────────────────────────────────────────────────────────

async function seed() {
  const transaction = client.transaction();

  // Create technologies
  for (const tech of technologies) {
    transaction.createOrReplace({
      _type: "technology",
      _id: tech._id,
      title: tech.title,
      slug: { _type: "slug", current: tech.slug },
      color: tech.color,
    });
  }

  // Create topics
  for (const topic of topics) {
    transaction.createOrReplace({
      _type: "topic",
      _id: topic._id,
      title: topic.title,
      slug: { _type: "slug", current: topic.slug },
    });
  }

  // Create personas
  for (const p of personas) {
    transaction.createOrReplace({
      _type: "persona",
      _id: p._id,
      title: p.title,
      slug: { _type: "slug", current: p.slug },
      description: p.description,
    });
  }

  // Create resources
  for (const r of resources) {
    const id = `resource-${r.slug}`;
    transaction.createOrReplace({
      _type: "resource",
      _id: id,
      title: r.title,
      slug: { _type: "slug", current: r.slug },
      description: r.description,
      contentType: r.contentType,
      technologies: r.technologies.map((ref) => ({
        _type: "reference",
        _ref: ref,
        _key: ref,
      })),
      topics: r.topics.map((ref) => ({
        _type: "reference",
        _ref: ref,
        _key: ref,
      })),
      personas: r.personas.map((ref) => ({
        _type: "reference",
        _ref: ref,
        _key: ref,
      })),
      publishedAt: r.publishedAt,
      featured: r.featured,
      duration: r.duration,
    });
  }

  console.log("Committing transaction...");
  const result = await transaction.commit();
  console.log(`Seeded ${result.results.length} documents.`);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
